# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='email',
            field=models.EmailField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='collector',
            name='email',
            field=models.EmailField(blank=True, max_length=1024, null=True),
        ),
    ]
