# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvpapp', '0003_generator_favorite_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofwaste', models.CharField(max_length=1024)),
                ('quantityofwaste', models.IntegerField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='generator',
            name='favorite_fruit',
        ),
    ]
