# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-04 18:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typerequired', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('glass', 'Glass')], default='plastic', max_length=1024)),
                ('contact', models.IntegerField(null=True)),
                ('address', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(null=True)),
                ('communityName', models.CharField(choices=[('household', 'Household'), ('industry', 'Industry'), ('market', 'Market'), ('office', 'Office')], default='household', max_length=1024)),
                ('typeofwaste', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('glass', 'Glass'), ('organic', 'Organic')], default='organic', max_length=1024)),
                ('address', models.TextField(blank=True, max_length=1024)),
                ('quantityofwaste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
